// Wordmark "interference" — generated by cfonts font "tiny" (filled blocks, ~48 col).
// True to the brand wordmark (logo/interference-wordmark.svg). No mark: the actual
// symbol (two wave sources) cannot be faithfully reproduced in ASCII.
export const WORDMARK: string[] = [
  " █ █▄ █ ▀█▀ █▀▀ █▀█ █▀▀ █▀▀ █▀█ █▀▀ █▄ █ █▀▀ █▀▀",
  " █ █ ▀█  █  ██▄ █▀▄ █▀  ██▄ █▀▄ ██▄ █ ▀█ █▄▄ ██▄",
];
